version: "3.9"
services: 
   backend: 
     build:  .
     ports: 
       - 3001:3000
     volumes: 
       - .:/app 
     depends_on: 
       - db 
   db: 
     image: mysql:8.0
     restart: always
     command: --default-authentication-plugin=mysql_native_password
     environment: 
        MYSQL_DATABASE: ambassador
        MYSQL_ROOT_HOST: "%"
        MYSQL_USER: daniel
        MYSQL_PASSWORD: Manassedaniel2001@
        MYSQL_ROOT_PASSWORD: Manassedaniel2001@
     ports:
       - 3307:3306
     volumes:
       - db-data:/var/lib/mysql  # You can define a named volume for data persistence
     
   redis: 
     image: redis 
     ports: 
        - 6379:6379

volumes:
   db-data:  # Define a named volume for MySQL data
